### PR TITLE
bump sbt and Scala versions

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
(you might consider adding this repo to https://github.com/scala-steward-org/scala-steward to get version-bump PRs automatically)

**Comment by SethTisue** [comment]
@lrodero hey, you around? 👀

**Comment by lrodero** [comment]
Hi, yes! Sorry I missed your first message (?). I'll take a look as soon as I can

**Comment by SethTisue** [comment]
rebased

**Review by lrodero — APPROVED** [review]
Thanks! :+1:

**Pull request merged**
